spring:
  datasource:
    url: jdbc:sqlserver://alpha-bookey.database.windows.net:1433;database=bkdb-alpha;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: bookey
    password: monoffice381#*!
  jpa:
    show-sql: true
    ddl-auto: none

oauth:
  google:
    client-id: 24555835397-1e38co4km52v79tqed51ob039skgl1ts.apps.googleusercontent.com
    client-secret: yL03DEbjjrMvJLALKJ0bAmHt
    redirect-uri: http://local.boo-key.com:8080/oauth/google

